---
config:
  theme: mc
  look: neo
  layout: dagre
---
classDiagram
direction LR
    class AbstractCustomLandmark {
        +\_\_len\_\_()
        +\_\_iter\_\_()
        +\_\_getattr\_\_()
        +\_\_getitem\_\_(idx)
	    +\_add\_landmark()
	    +as_landmark_list()
    }
    class CustomLandmarkBase {
	    +\_\_init\_subclass\_\_(cls,**kwargs)
    }
    class CustomLandmark {
	    +_register\_custom\_points()
    }
    class DefaultCustomLandmark {
        +NECK
        +THORAX
        +LEFT_RIB
        +RIGHT_RIB
        +MIDDLE_HIP
        +MIDDLE_SHOULDER
        +calc_neck()
        +calc_thorax()
        +calc_left_rib()
        +calc_right_rib()
        +calc_middle_hip()
        +calc_middle_shoulder()
        +\_middle(p1,p2)
    }
    class LandmarkRef {
	    +value
	    +\_\_iter\_\_()
        +\_\_repr\_\_()
	    +\_\_getitem\_\_(idx)
    }
    class point {
        +wrapper(fn)
    }
	<<Mixin>> CustomLandmarkBase
	<<decorator>> point
    CustomLandmark --|> AbstractCustomLandmark
    CustomLandmark --|> CustomLandmarkBase
    DefaultCustomLandmark --|> CustomLandmark
    CustomLandmarkBase --> LandmarkRef : returns
    CustomLandmark --> point : uses