---
config:
  theme: mc
  look: neo
  layout: dagre
---
classDiagram
direction TB
	namespace Usage {
        class Main {
	        video_capture
	        helloworld
        }
        class HelloWorld {
	        +\_middle_shoulder()
	        +\_neck()
        }
	}
	namespace virtual_landmark {
        class AbstractLandmark {
	        +\_\_len\_\_()
	        +\_\_iter\_\_()
	        +\_\_getitem\_\_(idx)
	        +\_\_contains\_\_(idx)
	        +\_add\_landmark(name,point)
	        +\_add\_connection(name,targets)
	        +as_landmark_list()
        }
        class VirtualLandmark {
	        +\_process\_virtual\_landmarks()
	        +virtual_landmark()
        }
        class VirtualPoseLandmark {
	        +\_\_repr\_\_()
	        +\_\_getitem\_\_(key)
	        +\_\_getattr\_\_(name)
	        +\_\_contains\_\_(item)
	        +\_load\_builtin\_landmarks()
	        +add(name,index)
        }
        class calculus {
	        +middle(p1,p2)
	        +projection(p1,p2,target)
	        +centroid(*points)
	        +mirror(p,axis_point)
	        +weighted_average(p1,p2,w1,w2)
	        +extend(p1,p2,factor)
	        +normalize(p1,p2)
	        +interpolate(p1,p2,alpha)
	        +bisector(p1,pivot,p2)
	        +rotate(p,axis_p1,axis_p2,angle)
        }
        class landmark {
	        +wrapper(fn)
        }
	}
	namespace drawing_utils {
        class Connections {
	        +CUSTOM_CONNECTION
	        +POSE_CONNECTIONS
	        +ALL_CONNECTIONS
        }
        class Style {
	        +get_extended_pose_landmarks_style(landmarks)
        }
	}

	<<package>> calculus
	<<decorator>> landmark
	<<package>> Style

    Main --> HelloWorld : uses
    Main --> calculus : uses
    Main --> Connections : uses
    Main --> Style : uses
    landmark ..> HelloWorld : decorate
    VirtualLandmark --|> AbstractLandmark
    AbstractLandmark --> VirtualPoseLandmark : uses
    HelloWorld --|> VirtualLandmark
