title: Virtual Landmark
description: Documentation for the virtual landmark extension system based on MediaPipe.
remote_theme: just-the-docs/just-the-docs
search_enabled: true
color_scheme: light

# Optional: repo link
repository_url: https://github.com/cvpose/virtual_landmark_python


plugins:
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-include

# Ative suporte a classes personalizadas (ex: {:.note})
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
  math_engine: mathjax

include:
  - _includes

default:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      mathjax: true