title: Virtual Landmark
description: Documentation for the virtual landmark extension system based on MediaPipe.
remote_theme: just-the-docs/just-the-docs
search_enabled: true
color_scheme: light

# Optional: repo link
repository_url: https://github.com/cvpose/virtual_landmark_python